version: '3.8'

services:
  db:
    image: postgres
    container_name: DataBase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=MyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks: 
        - mynetwork

  api:
    container_name: API_Assinadora
    ports:
      - 80:80
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - "db"
    networks:
      - mynetwork

  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - mynetwork
     
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local

networks:
  mynetwork:
     driver: bridge